// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function IsProcessing() {
  return window['go']['main']['App']['IsProcessing']();
}

export function ProcessFiles(arg1) {
  return window['go']['main']['App']['ProcessFiles'](arg1);
}

export function ScanDirectory(arg1, arg2) {
  return window['go']['main']['App']['ScanDirectory'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
