// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelProcessing():Promise<void>;

export function GetProgress():Promise<models.Progress>;

export function IsProcessing():Promise<boolean>;

export function ProcessFiles(arg1:models.ProcessOptions):Promise<void>;

export function ScanDirectory(arg1:string,arg2:boolean):Promise<Array<models.FileInfo>>;

export function SelectDirectory():Promise<string>;
